#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.11.1"
hooks = [
  # Ensure that the lockfile is up to date
  { id = "uv-lock" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.7"
hooks = [
  # Check code and apply automatic fixes where possible
  { id = "ruff-check", args = ["--fix"] },
  # Format code
  { id = "ruff-format" },
]

[[repos]]
repo = "local"
hooks = [
  # Run `uvx ty check` to perform type checking
  # A pre-commit hook isn't available yet: https://github.com/astral-sh/ty/issues/269
  { id = "ty-check", name = "ty check", language = "system", entry = "uv run ty check", pass_filenames = false, types = [
    "python",
  ] },
]

[[repos]]
repo = "https://github.com/netromdk/vermin"
rev = "v1.8.0"
hooks = [
  { id = "vermin"}
]
